cookie:
  expiry_days: 30
  key: abcdef_secret_key
  name: channelx_cookie
credentials:
  usernames:
    sujit:
      email: sujit@gmail.com
      first_name: Sujit
      last_name: Kumar
      password: sujit123
    creator1:
      email: creator@gmail.com
      first_name: Rohan
      last_name: Sharma
      password: sharma123
